### ISSUE TITLE
Missing sprout-base-fields forms twig file

### ISSUE THREAD

**Issue by SamHoltby** [barrelstrength/craft-sprout-reports#77]
### Description 
Just installed Sprout Reports after buying the license. Once I click on new report through either Data Sources or Reports I get the below error.

`Unable to find the template “sprout-base-fields/_includes/forms” in "sprout-base-reports/reports/_edit" at line 5.`

### Steps to reproduce
1. Install Sprout Reports 1.2.7
2. Click on New Report from either the Reports or Data Sources. 

### Additional info
- PHP | 7.2.6
- Craft Pro | 3.2.7
- Craft Commerce | 2.1.9
- Sprout Reports | 1.2.7

**Comment by beeldr** [comment]
Same issue: 

- PHP | 7.1.12
- Craft Pro |  3.4.4.1
- Craft Commere | 2.2.14
- Sprout Reports | 1.3.0

**Comment by BenParizek** [comment]
@SamHoltby @beeldr 

Thanks for the heads up. I've just released Sprout Reports v1.3.1 which should resolve this issue. Let me know if you run into anything else.

**Comment by iapparatus** [comment]
I'm having the same issue. Just upgraded both Craft, and Sprout Reports to the latest.

PHP | 7.2.5
Craft Pro | 3.4.5
Sprout Reports | 1.3.1

**Comment by BenParizek** [comment]
@iapparatus The error message here is saying that a particular template in the `barrelstrength/sprout-base-fields` package is not being found. 

Sprout Reports v1.3.1 requires `barrelstrength/sprout-base-reports:^1.4.1` and Sprout Base Reports v1.3.1 requires `barrelstrength/sprout-base-fields:^1.3.0` which includes the template that the error is saying does not exist, which should not be true if everything was installed correctly.

If you just updated, can you clear cache and see if it may just be a caching issue? If you're still seeing the issue, can you confirm if you can find Sprout Base Fields in your vendor folder and if the forms file is there? You should be able to find that file here:

`vendor/barrelstrength/sprout-base-fields/src/templates/_includes/forms.twig`

**Comment by iapparatus** [comment]
@BenParizek Yes, cleared all caches through the control panel twice and restarted the server. 

Confirmed that everything is updated and the template is there.

![Screenshot 2020-02-09 11 31 35](https://user-images.githubusercontent.com/4418188/74106027-11a92580-4b31-11ea-9c63-2eb2a0d0cb53.png)

**Comment by iapparatus** [comment]
I also just uninstalled and installed Sprout Reports again but still getting the same error.

**Comment by fireboxcreative** [comment]
Same issue.

Craft PRO 3.4.5 
Sprout Reports 1.3.1

Cache cleared, and the template is in the vendor folder at: `vendor/barrelstrength/sprout-base-fields/src/templates/_includes/forms.twig`

**Comment by BenParizek** [comment]
Hi folks. With the number of you reporting this I trust something is going on but I haven't been able to recreate it yet. It's odd that you are all receiving this while also being able to find the file that claims that it is missing.

Would anybody be available to troubleshoot in real time on a screenshare to help get to the bottom of this? I'm BenParizek on Craft Discord or let me know what works for you via a direct email: sprout@barrelstrengthdesign.com

**Comment by BenParizek** [comment]
Until I have a chance to connect with someone and troubleshoot this, if you are experiencing this, here are a few things you may want to consider:

1. Try to clear Craft's Template Caches. Sometimes after an update Craft will need a refresh before updates in plugin templates are recognized. From the comments above, this probably won't solve anything.

2. Check to see that you have the correct packages installed in your vendor folder. The version number is in each packages composer.json file. The packages you'll want to see are:

- vendor/barrelstrength/sprout-reports:v1.3.1
- vendor/barrelstrength/sprout-base-fields:v1.3.0
- vendor/barrelstrength/sprout-base-reports:v1.4.1
- vendor/barrelstrength/sprout-base:v5.1.0

3. If the packages look incorrect, try deleting the `/vendor` folder and the `composer.lock` file and re-running `composer install` which should pull in an up to date version of all of the packages.

Outside of that, I'll need to get more info before I can troubleshoot further. In my tests, I am able to install a fresh copy of Sprout Reports from the plugin store and don't see this error, so whatever is going on is likely more specific to something in certain environments.

**Comment by iapparatus** [comment]
@BenParizek I will go through these steps later today and if it doesn't work then will connect re: screen share. Thanks!

**Comment by BenParizek** [comment]
Hi Folks. I received a bit more info from someone directly and have been able to recreate the error. I'm looking into it.

**Comment by BenParizek** [comment]
@SamHoltby @beeldr @iapparatus @fireboxcreative 

I've just released Sprout Reports v1.3.2 which should resolve this issue and gets the fields template registered properly now. 

Thanks for the info while helping me track this down.
